### ISSUE TITLE
404 on page refresh / direct link

### ISSUE THREAD

**Issue by eithe** [enonic/app-office-league#468]
Hi and thanks for creating this - we use it a lot at our office :)

For the last 1-2 weeks we've experienced a 404 issue if you use a direct link to a league or if you refresh the page.

To reproduce:

1) Go to https://officeleague.rocks/app/leagues
2) Click on one of your leagues, e.g. https://officeleague.rocks/app/leagues/geodata
3) Refresh the page (F5) and you get a white 404 error page with grey text; "D'oh! 404 - Not Found"

The same thing occurs if you use a direct link to a league (like the one in step 2 above), or to the players page, e.g. https://officeleague.rocks/app/leagues/enonic%20foos/players

Any chance you could take a look at this if you are able to reproduce it?

**Comment by poi33** [comment]
Thanks for reporting this. 👍  
It is really helpful that you reported the specific links that don't work. 
It should not be a lot of work to add the links to those pages. 
If you find any other pages that do not work with direct links please add them in this issue.

**Comment by eithe** [comment]
Thanks @poi33. Looks to be everything after the league name so:
https://officeleague.rocks/app/leagues/geodata
https://officeleague.rocks/app/leagues/geodata/players
https://officeleague.rocks/app/leagues/geodata/teams
https://officeleague.rocks/app/leagues/geodata/games

**Comment by poi33** [comment]
@eithe this is fixed an live now. If you find any more issues with 404 pages just comment on this issue again

**Comment by eithe** [comment]
Great that you are on this @poi33 :) I'm still getting 404 for the links above, but I'll wait an hour or so and try again :)

**Comment by poi33** [comment]
https://officeleague.rocks/app/leagues/geodata should be available and no 404. 
The other links above are invalid. 
Team links look liek this: 
https://officeleague.rocks/app/teams/eido%20og%20anders 
or 
https://officeleague.rocks/app/teams/different%20pigeons
They follow the structure: 
app/teams/{name} 
And games: 
https://officeleague.rocks/app/games/a063d572-cf15-4069-8bc2-8d2c303b11a5
app/games/{gameid}

**Comment by eithe** [comment]
That's correct; https://officeleague.rocks/app/leagues/geodata works now, but it would be great that the direct link to the list of players also worked if possible (we have that on a display in our office :))

![image](https://user-images.githubusercontent.com/204129/129858758-9f151d8a-3931-4428-ba72-514895e83319.png)
![image](https://user-images.githubusercontent.com/204129/129858801-b99d1f0c-b90d-4bc5-babd-868f522940fa.png)

**Comment by poi33** [comment]
Seems you know the system links better then i do 😅 
I'll add the full page overview links to the system.
